# Generated by Django 4.2.11 on 2024-08-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_last_updated_inventory_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('received_by', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('putaway_location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], max_length=100)),
                ('putaway_section', models.CharField(blank=True, choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
    ]
