# Generated by Django 4.2.11 on 2024-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_receiving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_info',
            new_name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(default='http://defaultwebsite.com'),
        ),
    ]
