# Generated by Django 4.2.11 on 2024-08-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_contact_info_supplier_address_supplier_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Putaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], max_length=50)),
                ('section', models.CharField(choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], max_length=50)),
                ('received_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.receiving')),
            ],
        ),
    ]
