# Generated by Django 4.2.11 on 2024-08-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_putaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='replenishment_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('source_location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], max_length=50)),
                ('destination_location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('replenishment_threshold', models.PositiveIntegerField(default=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
