# Generated by Django 4.2.11 on 2024-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], max_length=50)),
                ('section_name', models.CharField(choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='internaltransfer',
            old_name='destination_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='replenishment_threshold',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='source_location',
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='destination_section',
            field=models.CharField(choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], default='Select Section', max_length=50),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='source_section',
            field=models.CharField(choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], default='Select Section', max_length=50),
        ),
    ]
