# Generated by Django 4.2.11 on 2024-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('Melbourne', 'Melbourne'), ('Kilmore', 'Kilmore'), ('Stawell', 'Stawell'), ('Shepparton', 'Shepparton'), ('Hamilton', 'Hamilton')], default='Select Location', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.CharField(choices=[('Section I', 'Section I'), ('Section II', 'Section II'), ('Section III', 'Section III'), ('Section IV', 'Section IV'), ('Section V', 'Section V')], default='Select Section', max_length=50),
        ),
        migrations.DeleteModel(
            name='Putaway',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
