# Generated by Django 4.2.11 on 2024-08-20 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_shipping_customer_remove_shipping_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
